import unittest
from tile_world.tile_world_writer.test_level_writer import TestTileWorldLevel
from validation.test_path_finder import TestPathFinder
from graph_structure.test_graph_node import TestGraphNode
from graph_to_level.test_unraveler import TestUnraveler

unittest.main()